### ISSUE TITLE
Please stop respond with "Success!" under any conditions

### ISSUE THREAD

**Issue by Yukinyaaa** [Osekai/osekai#133]
```js
fetch("https://osekai.net/profiles/api/goals.php", {
  "headers": {
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
  },
  "body": "Value=Not_a_value&Gamemode=osu&Type=Medals",
  "method": "POST",
});
```
In fact, [it returns "Success"](https://github.com/Osekai/osekai/blob/eb46305e6e0b05ce045e996a1dc857a5e11b7985/profiles/api/goals.php#L7) even though it has **not been added**.

**Comment by yuzupon1133** [comment]
https://github.com/Osekai/osekai/blob/7b0ac4eda41e2816ad0b62f68bc08dfe8820ba8b/global/api/notification_system.php#L11
https://github.com/Osekai/osekai/blob/3559d1398b1aee1cbf5665621e4e1b35dee88273/profiles/api/goals.php#L7
https://github.com/Osekai/osekai/blob/3559d1398b1aee1cbf5665621e4e1b35dee88273/profiles/api/timeline.php#L8
https://github.com/Osekai/osekai/blob/4069f5019b26dbd8acbc14acfd2e1e353cc8c923/medals/api/beatmaps.php#L32
https://github.com/Osekai/osekai/blob/3559d1398b1aee1cbf5665621e4e1b35dee88273/medals/api/medals.php#L36
...

At some point, the accepted type might change from, say, numbers to text. To prevent this, it is recommended to add a condition to all "Success!" responds.

But I don't want you to expend that effort to address this issue because it's not important.

**Comment by yuzupon1133** [comment]
I'm sorry I'm such a pain in the ass😥
